version: "3.8"

services:
   frontend:
      build:
         context: ../frontend
         dockerfile: Dockerfile
      image: ${DOCKER_USERNAME:-usuario}/mi-proyecto-frontend:latest
      container_name: frontend
      ports:
         - "80:80"
      depends_on:
         - auth
         - api
      networks:
         - app-network
      restart: unless-stopped

   auth:
      build:
         context: ../auth
         dockerfile: Dockerfile
      image: ${DOCKER_USERNAME:-usuario}/mi-proyecto-auth:latest
      container_name: auth
      ports:
         - "8080:8080"
      environment:
         - SPRING_PROFILES_ACTIVE=docker
         - SERVER_PORT=8080
      networks:
         - app-network
      restart: unless-stopped

   api:
      build:
         context: ../api
         dockerfile: Dockerfile
      image: ${DOCKER_USERNAME:-usuario}/mi-proyecto-api:latest
      container_name: api
      ports:
         - "8082:8082"
      environment:
         - SPRING_PROFILES_ACTIVE=docker
         - SERVER_PORT=8082
      depends_on:
         - auth
      networks:
         - app-network
      restart: unless-stopped

   jenkins:
      image: jenkins/jenkins:lts
      container_name: jenkins
      ports:
         - "8083:8080"
         - "50000:50000"
      volumes:
         - jenkins_home:/var/jenkins_home
         - /var/run/docker.sock:/var/run/docker.sock
      environment:
         - JENKINS_OPTS="--httpPort=8080"
         - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
      user: jenkins
      networks:
         - app-network
      restart: unless-stopped

networks:
   app-network:
      driver: bridge

volumes:
   jenkins_home:
