version: "3.8"

services:
   # API Spring Boot
   api:
      build:
         context: ../api
         dockerfile: Dockerfile
      container_name: api
      ports:
         - 8082:8082
      environment:
         - SPRING_DATA_MONGODB_URI=mongodb+srv://eriktortarod:PHyExF6fO46fPp7H@justdocit.1k27pyp.mongodb.net/apidb
         - SPRING_DATA_MONGODB_DATABASE=apidb
      networks:
         - app_network

   # Auth Spring Boot
   auth:
      build:
         context: ../auth
         dockerfile: Dockerfile
      container_name: auth
      ports:
         - 8080:8080
      environment:
         - SPRING_DATA_MONGODB_URI=mongodb+srv://eriktortarod:PHyExF6fO46fPp7H@justdocit.1k27pyp.mongodb.net/authdb
         - SPRING_DATA_MONGODB_DATABASE=authdb
         - IS_DOCKER=true
         - SPRING_APPLICATION_JSON={"app":{"frontend":{"url":"http://localhost:3001"}}}
      networks:
         - app_network

   # Frontend React TypeScript Vite
   frontend:
      build:
         context: ../frontend
         dockerfile: Dockerfile
         args:
            - VITE_API_URL=http://localhost:8080
            - VITE_DOCS_URL=http://localhost:8082
            - VITE_ENVIROMENT=PROD
      container_name: frontend
      ports:
         - 3001:80
      networks:
         - app_network
      depends_on:
         - api
         - auth

networks:
   app_network:
      name: app_network
