version: "3.8"

services:
   # MongoDB
   mongodb:
      image: mongo
      container_name: mongodb
      hostname: mongo
      ports:
         - 27018:27017
      volumes:
         - data:/data
      environment:
         - MONGO_INITDB_ROOT_USERNAME=rootuser
         - MONGO_INITDB_ROOT_PASSWORD=rootpass
      networks:
         app_network:
            aliases:
               - mongo

   mongo-express:
      image: mongo-express
      container_name: mongo-express
      restart: always
      ports:
         - 8081:8081
      environment:
         - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
         - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
         - ME_CONFIG_MONGODB_SERVER=mongo
         - ME_CONFIG_BASICAUTH_USERNAME=admin
         - ME_CONFIG_BASICAUTH_PASSWORD=pass
      depends_on:
         - mongodb
      networks:
         - app_network

   # API Spring Boot
   api:
      build:
         context: ../api
         dockerfile: Dockerfile
      container_name: api
      ports:
         - 8082:8082
      environment:
         - SPRING_DATA_MONGODB_HOST=mongodb
         - SPRING_DATA_MONGODB_PORT=27017
         - SPRING_DATA_MONGODB_USERNAME=rootuser
         - SPRING_DATA_MONGODB_PASSWORD=rootpass
         - SPRING_DATA_MONGODB_DATABASE=apidb
         - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      networks:
         - app_network
      depends_on:
         - mongodb

   # Auth Spring Boot
   auth:
      build:
         context: ../auth
         dockerfile: Dockerfile
      container_name: auth
      ports:
         - 8080:8080
      environment:
         - SPRING_DATA_MONGODB_HOST=mongodb
         - SPRING_DATA_MONGODB_PORT=27017
         - SPRING_DATA_MONGODB_USERNAME=rootuser
         - SPRING_DATA_MONGODB_PASSWORD=rootpass
         - SPRING_DATA_MONGODB_DATABASE=authdb
         - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
         - IS_DOCKER=true
         - SPRING_APPLICATION_JSON={"app":{"frontend":{"url":"http://localhost:5173"}}}
      networks:
         - app_network
      depends_on:
         - mongodb

   # Frontend React TypeScript Vite
   frontend:
      build:
         context: ../frontend
         dockerfile: Dockerfile
      container_name: frontend
      ports:
         - 5173:80 # Mapeamos al puerto 80 interno
      environment:
         - VITE_API_URL=http://localhost:8080
      networks:
         - app_network
      depends_on:
         - api
         - auth

volumes:
   data: {}

networks:
   app_network:
      name: app_network
