version: "3.8"

services:
   auth:
      build:
         context: ../auth
         dockerfile: Dockerfile
      container_name: auth
      ports:
         - 8080:8080
      environment:
         - SPRING_DATA_MONGODB_HOST=mongodb
         - SPRING_DATA_MONGODB_PORT=27017
         - SPRING_DATA_MONGODB_USERNAME=rootuser
         - SPRING_DATA_MONGODB_PASSWORD=rootpass
         - SPRING_DATA_MONGODB_DATABASE=authdb
         - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      networks:
         - app_network
      depends_on:
         - mongodb

networks:
   app_network:
      external: true
      name: app_network
