version: "3.8"

services:
   api:
      build:
         context: ../api
         dockerfile: Dockerfile
      container_name: api
      ports:
         - 8082:8080
      environment:
         - SPRING_DATA_MONGODB_HOST=mongodb
         - SPRING_DATA_MONGODB_PORT=27017
         - SPRING_DATA_MONGODB_USERNAME=rootuser
         - SPRING_DATA_MONGODB_PASSWORD=rootpass
         - SPRING_DATA_MONGODB_DATABASE=apidb
         - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      networks:
         - app_network
      depends_on:
         - mongodb

networks:
   app_network:
      external: true
      name: app_network
