version: "3.8"

services:
   frontend:
      build:
         context: ../frontend
         dockerfile: Dockerfile
      container_name: frontend
      ports:
         - 5173:80 # Mapeamos al puerto 80 interno
      environment:
         - VITE_API_URL=http://localhost:8080
      networks:
         - app_network

networks:
   app_network:
      external: true
      name: app_network
