# API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
   name: api
   namespace: my-app
spec:
   selector:
      matchLabels:
         app: api
   template:
      metadata:
         labels:
            app: api
      spec:
         containers:
            - name: api
              image: eriktortarod/docker-api:latest
              ports:
                 - containerPort: 8082
              env:
                 - name: SPRING_APPLICATION_NAME
                   value: api
                 - name: SERVER_PORT
                   value: "8082"
                 # Logs
                 - name: LOGGING_LEVEL_COM_API_API_SERVICE_CODEDOCUMENTATIONSERVICE
                   value: "DEBUG"
                 - name: LOGGING_LEVEL_COM_API_API_SERVICE_TYPESCRIPTDOCUMENTATIONPARSER
                   value: "DEBUG"
                 # Configuración de seguridad básica
                 - name: SPRING_SECURITY_USER_NAME
                   value: user
                 - name: SPRING_SECURITY_USER_PASSWORD
                   valueFrom:
                      secretKeyRef:
                         name: app-secrets
                         key: SPRING_SECURITY_USER_PASSWORD
                 # Configuración MongoDB Atlas
                 - name: SPRING_DATA_MONGODB_URI
                   value: mongodb+srv://eriktortarod:PHyExF6fO46fPp7H@justdocit.1k27pyp.mongodb.net/justdocit
                 # Claves de encriptación y JWT
                 - name: ENCRYPTION_SECRET
                   valueFrom:
                      secretKeyRef:
                         name: app-secrets
                         key: ENCRYPTION_SECRET
                 - name: JWT_SECRET_KEY1
                   valueFrom:
                      secretKeyRef:
                         name: app-secrets
                         key: JWT_SECRET_KEY1
                 - name: JWT_SECRET_KEY2
                   valueFrom:
                      secretKeyRef:
                         name: app-secrets
                         key: JWT_SECRET_KEY2
                 # URL del frontend - será actualizada después del deploy
                 - name: FRONTEND_URL
                   value: "FRONTEND_LOADBALANCER_URL"
---
# API Service - LoadBalancer para EKS
apiVersion: v1
kind: Service
metadata:
   name: api
   namespace: my-app
   annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
   selector:
      app: api
   ports:
      - port: 8082
        targetPort: 8082
   type: LoadBalancer
