apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-vite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-vite
  template:
    metadata:
      labels:
        app: frontend-vite
    spec:
      containers:
      - name: frontend
        image: eriktortarod/docker-frontend:latest
        ports:
        - containerPort: 5173  # Puerto que expone Vite en desarrollo
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-vite
  ports:
  - port: 80           # Puerto expuesto externamente 
    targetPort: 5173   # Puerto interno de Vite
  type: LoadBalancer