# Mongo Express Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
   name: mongo-express
   namespace: my-app
spec:
   replicas: 1
   selector:
      matchLabels:
         app: mongo-express
   template:
      metadata:
         labels:
            app: mongo-express
      spec:
         containers:
            - name: mongo-express
              image: mongo-express:latest
              ports:
                 - containerPort: 8081
              env:
                 - name: ME_CONFIG_MONGODB_ADMINUSERNAME
                   valueFrom:
                      secretKeyRef:
                         name: mongodb-secret
                         key: MONGO_INITDB_ROOT_USERNAME
                 - name: ME_CONFIG_MONGODB_ADMINPASSWORD
                   valueFrom:
                      secretKeyRef:
                         name: mongodb-secret
                         key: MONGO_INITDB_ROOT_PASSWORD
                 - name: ME_CONFIG_MONGODB_SERVER
                   value: mongodb
                 - name: ME_CONFIG_BASICAUTH_USERNAME
                   valueFrom:
                      secretKeyRef:
                         name: mongo-express-secret
                         key: ME_CONFIG_BASICAUTH_USERNAME
                 - name: ME_CONFIG_BASICAUTH_PASSWORD
                   valueFrom:
                      secretKeyRef:
                         name: mongo-express-secret
                         key: ME_CONFIG_BASICAUTH_PASSWORD
                 - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
                   value: "true"
              resources:
                 requests:
                   memory: "128Mi"
                   cpu: "100m"
                 limits:
                   memory: "256Mi"
                   cpu: "200m"
---
# Mongo Express Service
apiVersion: v1
kind: Service
metadata:
   name: mongo-express
   namespace: my-app
   annotations:
     service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
   selector:
      app: mongo-express
   ports:
      - port: 8081
        targetPort: 8081
   type: LoadBalancer