# Auth Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
   name: auth
   namespace: my-app
spec:
   selector:
      matchLabels:
         app: auth
   template:
      metadata:
         labels:
            app: auth
      spec:
         containers:
            - name: auth
              image: eriktortarod/docker-auth:latest
              ports:
                 - containerPort: 8080
              env:
                 - name: SPRING_APPLICATION_NAME
                   value: auth
                 # Configuración de seguridad básica
                 - name: SPRING_SECURITY_USER_NAME
                   value: user
                 - name: SPRING_SECURITY_USER_PASSWORD
                   valueFrom:
                      secretKeyRef:
                         name: app-secrets
                         key: SPRING_SECURITY_USER_PASSWORD
                 # Configuración OAuth GitHub
                 - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID
                   valueFrom:
                      secretKeyRef:
                         name: app-secrets
                         key: GITHUB_CLIENT_ID
                 - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET
                   valueFrom:
                      secretKeyRef:
                         name: app-secrets
                         key: GITHUB_CLIENT_SECRET
                 - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_SCOPE
                   value: "read:user,user:email,repo"
                 # Configuración MongoDB
                 - name: SPRING_DATA_MONGODB_HOST
                   value: mongodb
                 - name: SPRING_DATA_MONGODB_PORT
                   value: "27017"
                 - name: SPRING_DATA_MONGODB_USERNAME
                   valueFrom:
                      secretKeyRef:
                         name: mongodb-secret
                         key: MONGO_INITDB_ROOT_USERNAME
                 - name: SPRING_DATA_MONGODB_PASSWORD
                   valueFrom:
                      secretKeyRef:
                         name: mongodb-secret
                         key: MONGO_INITDB_ROOT_PASSWORD
                 - name: SPRING_DATA_MONGODB_DATABASE
                   value: justdocit
                 - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
                   value: admin
                 - name: SPRING_DATA_MONGODB_AUTO_INDEX_CREATION
                   value: "true"
                 # Claves de encriptación y JWT
                 - name: ENCRYPTION_SECRET
                   valueFrom:
                      secretKeyRef:
                         name: app-secrets
                         key: ENCRYPTION_SECRET
                 - name: JWT_SECRET_KEY1
                   valueFrom:
                      secretKeyRef:
                         name: app-secrets
                         key: JWT_SECRET_KEY1
                 - name: JWT_SECRET_KEY2
                   valueFrom:
                      secretKeyRef:
                         name: app-secrets
                         key: JWT_SECRET_KEY2
                 # URL del frontend
                 - name: FRONTEND_URL
                   value: "http://MINIKUBE_IP:30173"
                 # Docker flag
                 - name: IS_DOCKER
                   value: "true"
---
# Auth Service
apiVersion: v1
kind: Service
metadata:
   name: auth
   namespace: my-app
spec:
   selector:
      app: auth
   ports:
      - port: 8080
        targetPort: 8080
        nodePort: 30080
   type: NodePort
