apiVersion: apps/v1
kind: Deployment
metadata:
   name: frontend
   namespace: my-app
spec:
   selector:
      matchLabels:
         app: frontend
   template:
      metadata:
         labels:
            app: frontend
      spec:
         containers:
            - name: frontend
              image: eriktortarod/docker-frontend:latest
              ports:
                 - containerPort: 80 # Cambiado de 3001 a 80
              env:
                 # URL para auth (puerto 8080)
                 - name: VITE_API_URL
                   value: "http://MINIKUBE_IP:30080"
                 # URL para api (puerto 8082)
                 - name: VITE_DOCS_URL
                   value: "http://MINIKUBE_IP:30082"
---
apiVersion: v1
kind: Service
metadata:
   name: frontend
   namespace: my-app
spec:
   selector:
      app: frontend
   ports:
      - port: 80 # Cambiado de 3001 a 80
        targetPort: 80 # Cambiado de 3001 a 80
        nodePort: 30173
   type: NodePort
