# Mongo Express Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
   name: mongo-express
   namespace: my-app
spec:
   selector:
      matchLabels:
         app: mongo-express
   template:
      metadata:
         labels:
            app: mongo-express
      spec:
         containers:
            - name: mongo-express
              image: mongo-express
              ports:
                 - containerPort: 8081
              env:
                 - name: ME_CONFIG_MONGODB_ADMINUSERNAME
                   valueFrom:
                      secretKeyRef:
                         name: mongodb-secret
                         key: MONGO_INITDB_ROOT_USERNAME
                 - name: ME_CONFIG_MONGODB_ADMINPASSWORD
                   valueFrom:
                      secretKeyRef:
                         name: mongodb-secret
                         key: MONGO_INITDB_ROOT_PASSWORD
                 - name: ME_CONFIG_MONGODB_SERVER
                   value: mongodb
                 - name: ME_CONFIG_BASICAUTH_USERNAME
                   valueFrom:
                      secretKeyRef:
                         name: mongo-express-secret
                         key: ME_CONFIG_BASICAUTH_USERNAME
                 - name: ME_CONFIG_BASICAUTH_PASSWORD
                   valueFrom:
                      secretKeyRef:
                         name: mongo-express-secret
                         key: ME_CONFIG_BASICAUTH_PASSWORD
                 - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
                   value: "true"
                 - name: ME_CONFIG_SITE_COOKIESECRET
                   value: "cookiesecret"
                 - name: ME_CONFIG_SITE_SESSIONSECRET
                   value: "sessionsecret"
---
# Mongo Express Service
apiVersion: v1
kind: Service
metadata:
   name: mongo-express
   namespace: my-app
spec:
   selector:
      app: mongo-express
   ports:
      - port: 8081
        targetPort: 8081
        nodePort: 30081
   type: NodePort
