name: Test PR

on:
   pull_request:
      branches:
         - dev
         - main

jobs:
   test:
      runs-on: ubuntu-latest
      defaults:
         run:
            working-directory: frontend/

      steps:
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: "22"
              cache: "npm"
              cache-dependency-path: frontend/package-lock.json

         - name: Install dependencies
           run: npm install

         - name: Run tests
           id: test
           run: |
              # Run tests with NO_COLOR=1 to disable ANSI colors
              NO_COLOR=1 npm run test > test-results.txt 2>&1
              echo "exit_code=$?" >> $GITHUB_OUTPUT

         - name: Read test results
           id: read-results
           run: |
              # Clean up the output and format it for GitHub
              sed -i 's/\x1b\[[0-9;]*m//g' test-results.txt  # Remove ANSI color codes
              sed -i 's/^[[:space:]]*//' test-results.txt    # Remove leading whitespace
              echo "results<<EOF" >> $GITHUB_OUTPUT
              cat test-results.txt >> $GITHUB_OUTPUT
              echo "EOF" >> $GITHUB_OUTPUT

         - name: Comment PR
           uses: actions/github-script@v7
           with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              script: |
                 const results = `${{ steps.read-results.outputs.results }}`;
                 const exitCode = ${{ steps.test.outputs.exit_code }};

                 const emoji = exitCode === 0 ? '✅' : '❌';
                 const status = exitCode === 0 ? 'passed' : 'failed';

                 # Extract test summary
                 const testSummary = results.match(/Test Files.*\n.*Tests.*\n.*Duration.*/s)?.[0] || '';

                 # Extract individual test results
                 const testResults = results.match(/✓.*\n/g) || [];

                 const comment = `
                 ${emoji} **Test Results**

                 Status: ${status}

                 **Test Summary:**
                 \`\`\`
                 ${testSummary}
                 \`\`\`

                 **Individual Tests:**
                 ${testResults.map(test => `- ${test.trim()}`).join('\n')}
                 `;

                 github.rest.issues.createComment({
                   issue_number: context.issue.number,
                   owner: context.repo.owner,
                   repo: context.repo.repo,
                   body: comment
                 });
